global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['${MONITOR_INDEXER}-monitor-node-exporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['${MONITOR_INDEXER}-monitor-cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['${MONITOR_INDEXER}-monitor-prometheus:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['${MONITOR_INDEXER}-monitor-pushgateway:9091']

  - job_name: 'index-node'
    scrape_interval: 5s
    static_configs:
      - targets: ['index-node:8040']

  - job_name: 'query-node'
    scrape_interval: 5s
    static_configs:
      - targets: ['query-node:8040']

  - job_name: 'indexer-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['${MONITOR_INDEXER}-indexer-service:7300']

  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets: ['${MONITOR_INDEXER}-monitor-grafana:3000']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - '${MONITOR_INDEXER}-monitor-alertmanager:9093'
