global:
  scrape_interval: 115s
  evaluation_interval: 115s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: "docker-host-alpha"

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# Alert Manager
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "graph-monitor-alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets: ['graph-monitor-grafana:3000']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['graph-monitor-node-exporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['graph-monitor-cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['graph-monitor-prometheus:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['graph-monitor-pushgateway:9091']
