{
 "title": "Autoagora",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Queries Failed vs OK per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(indexer_service_queries_failed[1m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(indexer_service_queries_ok[1m]))",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "GRT / second over all subgraphs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(Fees_total[10m])) * 10^-18",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries by subgraph per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (deployment) (rate(indexer_service_queries_total[1m]))",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "GRT / second per subgraph",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(Fees_total{}[60s]) * 10^-18",
     "legendFormat": "{{subgraph}}"
    }
   ]
  },
  {
   "title": "Bandit mean",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    { "expr": "bandit_mean", "legendFormat": "{{subgraph}}" }
   ]
  },
  {
   "title": "Bandit standard deviation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    { "expr": "bandit_stddev", "legendFormat": "{{subgraph}}" }
   ]
  },
  {
   "title": "Bandit sampled price multiplier",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    { "expr": "bandit_price_multiplier", "legendFormat": "{{subgraph}}" }
   ]
  },
  {
   "title": "Bandit reward",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    { "expr": "bandit_reward", "legendFormat": "{{subgraph}}" }
   ]
  }
 ]
}