{
 "title": "Indexing Status Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Block ingestion rate",
   "type": "timeseries",
   "description": "If ingestion falls to zero there is an issue with the graph nodes processing new blocks. Check health of blockchain nodes",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "deriv(ethereum_chain_head_number{job=\"index-node\"}[1m]) * 60",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Networks",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  name,\n  head_block_number AS \"block_number\",\n  head_block_hash AS \"block_hash\"\nFROM ethereum_networks\nORDER BY name;"
    }
   ]
  },
  {
   "title": "Healthy Subgraphs Status",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  subgraph.name || \r\n    CASE \r\n      WHEN subgraph.pending_version = version.id THEN ' (P)'\r\n      WHEN subgraph.current_version = version.id THEN ' (C)'\r\n      ELSE ' (Unknown)' \r\n    END AS subgraph_name,\r\n  deployment.deployment,\r\n  schema.id as schema_id,\r\n  schema.created_at as created,\r\n  shard as shard,\r\n  active as active,\r\n  REPLACE(assignment.node_id, '', '') AS node_id,\r\n  deployment.synced::text AS is_synced,\r\n  network.name AS network_name,\r\n  (network.head_block_number - deployment.latest_ethereum_block_number) AS blocks_behind_network,\r\n  CASE \r\n    WHEN network.name = 'mainnet' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 5)::text\r\n    WHEN network.name = 'rinkeby' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 4)::text\r\n    WHEN network.name = 'kovan' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 15)::text\r\n    WHEN network.name = 'poa-core' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 12)::text\r\n    WHEN network.name = 'ropsten' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 2)::text\r\n    WHEN network.name = 'arbitrum-one' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 230)::text\r\n    WHEN network.name = 'arbitrum-sepolia' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 230)::text\r\n    WHEN network.name = 'matic' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 30)::text\r\n    WHEN network.name = 'base' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 30)::text\r\n    WHEN network.name = 'optimism' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 30)::text\r\n    WHEN network.name = 'avalanche' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 30)::text\r\n    WHEN network.name = 'fantom' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 40)::text\r\n    WHEN network.name = 'celo' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 12)::text\r\n    WHEN network.name = 'gnosis' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 12)::text\r\n    WHEN network.name = 'bsc' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 20)::text\r\n    WHEN network.name = 'linea' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 30)::text\r\n    WHEN network.name = 'scroll' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 20)::text\r\n    WHEN network.name = 'boba' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 30)::text\r\n    WHEN network.name = 'boba-bnb' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 5)::text\r\n    WHEN network.name = 'moonbeam' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 10)::text\r\n    ELSE 'N/A' \r\n  END AS lag\r\nFROM\r\n  subgraphs.subgraph_deployment AS deployment,\r\n  subgraphs.subgraph_deployment_assignment AS assignment,\r\n  subgraphs.subgraph_version AS version,\r\n  subgraphs.subgraph AS subgraph,\r\n  ethereum_networks AS network,\r\n  deployment_schemas AS schema\r\nWHERE\r\n  subgraph.id = version.subgraph\r\n  AND version.id IN (subgraph.pending_version, subgraph.current_version)\r\n  AND assignment.id = schema.id\r\n  AND schema.id = deployment.id\r\n  AND version.deployment = deployment.deployment\r\n  AND NOT deployment.failed\r\n  AND network.name = schema.network\r\n  AND assignment.node_id != 'removed'\r\nORDER BY\r\n  blocks_behind_network DESC,\r\n  subgraph_name;\r\n"
    }
   ]
  },
  {
   "title": "Paused Subgraphs Status",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  subgraph.name || \r\n    CASE \r\n      WHEN subgraph.pending_version = version.id THEN ' (P)'\r\n      WHEN subgraph.current_version = version.id THEN ' (C)'\r\n      ELSE ' (Unknown)' \r\n    END AS subgraph_name,\r\n  deployment.deployment,\r\n  schema.id as schema_id,\r\n  schema.created_at as created,\r\n  shard as shard,\r\n  active as active,\r\n  REPLACE(assignment.node_id, '', '') AS node_id,\r\n  deployment.synced::text AS is_synced,\r\n  network.name AS network_name,\r\n  (network.head_block_number - deployment.latest_ethereum_block_number) AS blocks_behind_network,\r\n  CASE \r\n    WHEN network.name = 'mainnet' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 5)::text\r\n    WHEN network.name = 'rinkeby' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 4)::text\r\n    WHEN network.name = 'kovan' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 15)::text\r\n    WHEN network.name = 'poa-core' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 12)::text\r\n    WHEN network.name = 'ropsten' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 2)::text\r\n    WHEN network.name = 'arbitrum-one' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 230)::text\r\n    WHEN network.name = 'arbitrum-sepolia' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 230)::text\r\n    WHEN network.name = 'matic' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 30)::text\r\n    WHEN network.name = 'base' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 30)::text\r\n    WHEN network.name = 'optimism' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 30)::text\r\n    WHEN network.name = 'avalanche' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 30)::text\r\n    WHEN network.name = 'fantom' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 40)::text\r\n    WHEN network.name = 'celo' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 12)::text\r\n    WHEN network.name = 'gnosis' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 12)::text\r\n    WHEN network.name = 'bsc' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 20)::text\r\n    WHEN network.name = 'linea' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 30)::text\r\n    WHEN network.name = 'scroll' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 20)::text\r\n    WHEN network.name = 'boba' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 30)::text\r\n    WHEN network.name = 'boba-bnb' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 5)::text\r\n    WHEN network.name = 'moonbeam' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 10)::text\r\n    ELSE 'N/A' \r\n  END AS lag\r\nFROM\r\n  subgraphs.subgraph_deployment AS deployment,\r\n  subgraphs.subgraph_deployment_assignment AS assignment,\r\n  subgraphs.subgraph_version AS version,\r\n  subgraphs.subgraph AS subgraph,\r\n  ethereum_networks AS network,\r\n  deployment_schemas AS schema\r\nWHERE\r\n  subgraph.id = version.subgraph\r\n  AND version.id IN (subgraph.pending_version, subgraph.current_version)\r\n  AND assignment.id = schema.id\r\n  AND schema.id = deployment.id\r\n  AND version.deployment = deployment.deployment\r\n  AND NOT deployment.failed\r\n  AND network.name = schema.network\r\n  AND assignment.node_id not like 'index_node_%'\r\nORDER BY\r\n  blocks_behind_network DESC,\r\n  subgraph_name;\r\n"
    }
   ]
  },
  {
   "title": "Deterministic Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "WITH ranked_errors AS (\n    SELECT \n        subgraph_id, \n        vid, \n        encode(block_hash, 'hex') AS block_hash, \n        message, \n        handler, \n        deterministic, \n        created_at,\n        ROW_NUMBER() OVER (PARTITION BY subgraph_id ORDER BY vid DESC) AS rnk\n    FROM subgraphs.subgraph_error\n    WHERE deterministic = true\n)\nSELECT \n    subgraph_id, \n    vid, \n    block_hash, \n    message, \n    handler, \n    deterministic, \n    created_at\nFROM ranked_errors\nWHERE rnk = 1\nORDER BY vid DESC;\n"
    }
   ]
  },
  {
   "title": "Non-Deterministic Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "targets": [
    {
     "rawSql": "WITH ranked_errors AS (\n    SELECT \n        subgraph_id, \n        vid, \n        encode(block_hash, 'hex') AS block_hash, \n        message, \n        handler, \n        deterministic, \n        created_at,\n        ROW_NUMBER() OVER (PARTITION BY subgraph_id ORDER BY vid DESC) AS rnk\n    FROM subgraphs.subgraph_error\n    WHERE deterministic = false\n)\nSELECT \n    subgraph_id, \n    vid, \n    block_hash, \n    message, \n    handler, \n    deterministic, \n    created_at\nFROM ranked_errors\nWHERE rnk = 1\nORDER BY vid DESC;\n"
    }
   ]
  },
  {
   "title": "All Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "rawSql": "WITH ranked_errors AS (\n    SELECT \n        subgraph_id, \n        vid, \n        encode(block_hash, 'hex') AS block_hash, \n        message, \n        handler, \n        deterministic, \n        created_at,\n        ROW_NUMBER() OVER (PARTITION BY subgraph_id ORDER BY vid DESC) AS rnk\n    FROM subgraphs.subgraph_error\n)\nSELECT \n    subgraph_id, \n    vid, \n    block_hash, \n    message, \n    handler, \n    deterministic, \n    created_at\nFROM ranked_errors\nWHERE rnk = 1\nORDER BY vid DESC;\n"
    }
   ]
  },
  {
   "title": "Subgraph Health",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \n    ds.name as deployment_schema,\n    ds.shard as deployment_shard,\n    ds.created_at as deployment_created_at,\n    sg.name as deployment_name,\n    sd.deployment as deployment,\n    substring(sm.repository, 20, 31) as git_repo,\n    sda.node_id as node_id,\n    sd.health as sub_health,\n    sd.failed as sub_failed,\n    sd.synced as sub_sync,\n    sd.latest_ethereum_block_number as last_block,\n    sd.entity_count as sub_entity,\n    size.total_bytes as size_total, \n    size.total_bytes as size_total_bytes, \n    sm.start_block_number as start_block, \n    encode(sm.start_block_hash, 'hex') as start_hash, \n    encode(sd.latest_ethereum_block_hash, 'hex') as last_hash,\n    sd.reorg_count as reorg_count, \n    sd.current_reorg_depth as curr_reorg_count, \n    sd.max_reorg_depth as max_reorg,\n    ds.network as network,\n    -- Removed subgraph_name, is_synced, and network_name\n    (network.head_block_number - sd.latest_ethereum_block_number) AS blocks_behind_network,\n    CASE \n        WHEN network.name = 'mainnet' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 5)::text\n        WHEN network.name = 'rinkeby' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 4)::text\n        WHEN network.name = 'kovan' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 15)::text\n        WHEN network.name = 'poa-core' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 12)::text\n        WHEN network.name = 'ropsten' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 2)::text\n        WHEN network.name = 'arbitrum-one' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 230)::text\n        WHEN network.name = 'arbitrum-sepolia' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 230)::text\n        WHEN network.name = 'matic' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 30)::text\n        WHEN network.name = 'base' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 30)::text\n        WHEN network.name = 'optimism' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 30)::text\n        WHEN network.name = 'avalanche' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 30)::text\n        WHEN network.name = 'fantom' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 40)::text\n        WHEN network.name = 'celo' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 12)::text\n        WHEN network.name = 'gnosis' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 12)::text\n        WHEN network.name = 'bsc' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 20)::text\n        WHEN network.name = 'linea' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 30)::text\n        WHEN network.name = 'scroll' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 20)::text\n        WHEN network.name = 'boba' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 30)::text\n        WHEN network.name = 'boba-bnb' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 5)::text\n        WHEN network.name = 'moonbeam' THEN ((network.head_block_number - sd.latest_ethereum_block_number) / 10)::text\n        ELSE 'N/A' \n    END AS lag\nFROM subgraphs.subgraph_deployment AS sd\nJOIN subgraphs.subgraph_manifest AS sm ON (sm.id = sd.id)\nJOIN public.deployment_schemas AS ds ON (ds.subgraph = sd.deployment)\nJOIN subgraphs.subgraph_version AS sv ON (sv.deployment = sd.deployment)\nJOIN subgraphs.subgraph AS sg ON (sv.id IN (sg.current_version, sg.pending_version)) -- Added subgraph JOIN\nLEFT JOIN subgraphs.subgraph_deployment_assignment AS sda ON (sda.id = sd.id)\nLEFT JOIN info.subgraph_sizes AS size ON (ds.name = size.name)\nJOIN ethereum_networks AS network ON (network.name = ds.network)\nORDER BY sd.id;\n"
    }
   ]
  },
  {
   "title": "Subgraph Node Assignments",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "rawSql": "select replace(node_id, '', '') as nodeId,\n       count(*) as num_assigned,\n       array_agg(id) as deployments\n  from subgraphs.subgraph_deployment_assignment\n group by node_id\n order by node_id asc;\n"
    }
   ]
  },
  {
   "title": "All Subgraphs Status",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  subgraph.name || \r\n    CASE \r\n      WHEN subgraph.pending_version = version.id THEN ' (P)'\r\n      WHEN subgraph.current_version = version.id THEN ' (C)'\r\n      ELSE ' (Unknown)' \r\n    END AS subgraph_name,\r\n  deployment.deployment,\r\n  schema.id as schema_id,\r\n  schema.created_at as created,\r\n  shard as shard,\r\n  active as active,\r\n  failed as failed,\r\n  REPLACE(assignment.node_id, '', '') AS node_id,\r\n  deployment.synced::text AS is_synced,\r\n  network.name AS network_name,\r\n  (network.head_block_number - deployment.latest_ethereum_block_number) AS blocks_behind_network,\r\n  CASE \r\n    WHEN network.name = 'mainnet' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 5)::text\r\n    WHEN network.name = 'rinkeby' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 4)::text\r\n    WHEN network.name = 'kovan' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 15)::text\r\n    WHEN network.name = 'poa-core' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 12)::text\r\n    WHEN network.name = 'ropsten' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 2)::text\r\n    WHEN network.name = 'arbitrum-one' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 230)::text\r\n    WHEN network.name = 'arbitrum-sepolia' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 230)::text\r\n    WHEN network.name = 'matic' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 30)::text\r\n    WHEN network.name = 'base' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 30)::text\r\n    WHEN network.name = 'optimism' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 30)::text\r\n    WHEN network.name = 'avalanche' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 30)::text\r\n    WHEN network.name = 'fantom' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 40)::text\r\n    WHEN network.name = 'celo' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 12)::text\r\n    WHEN network.name = 'gnosis' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 12)::text\r\n    WHEN network.name = 'bsc' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 20)::text\r\n    WHEN network.name = 'linea' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 30)::text\r\n    WHEN network.name = 'scroll' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 20)::text\r\n    WHEN network.name = 'boba' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 30)::text\r\n    WHEN network.name = 'boba-bnb' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 5)::text\r\n    WHEN network.name = 'moonbeam' THEN ((network.head_block_number - deployment.latest_ethereum_block_number) / 10)::text\r\n    ELSE 'N/A' \r\n  END AS lag\r\nFROM\r\n  subgraphs.subgraph_deployment AS deployment,\r\n  subgraphs.subgraph_deployment_assignment AS assignment,\r\n  subgraphs.subgraph_version AS version,\r\n  subgraphs.subgraph AS subgraph,\r\n  ethereum_networks AS network,\r\n  deployment_schemas AS schema\r\nWHERE\r\n  subgraph.id = version.subgraph\r\n  AND version.id IN (subgraph.pending_version, subgraph.current_version)\r\n  AND assignment.id = schema.id\r\n  AND schema.id = deployment.id\r\n  AND version.deployment = deployment.deployment\r\n  AND network.name = schema.network\r\nORDER BY\r\n  blocks_behind_network DESC,\r\n  subgraph_name;\r\n"
    }
   ]
  }
 ]
}