{
 "title": "Postgres Sizes",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "shard", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Chain sizes",
   "type": "table",
   "description": "Data from a materialized view that is refreshed only occasionally",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nselect c.name, table_schema, table_name, row_estimate, total_bytes, total_bytes - index_bytes - toast_bytes as table_bytes, index_bytes, toast_bytes\n  from info.chain_sizes sz, chains c\n where sz.table_schema = c.namespace\norder by total_bytes desc"
    }
   ]
  },
  {
   "title": "Subgraph sizes",
   "type": "table",
   "description": "Data from a materialized view that is refreshed only occasionally",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nselect name, subgraph, row_estimate, total_bytes, total_bytes - index_bytes - toast_bytes as table_bytes, index_bytes, toast_bytes\n  from info.subgraph_sizes\norder by total_bytes desc"
    }
   ]
  },
  {
   "title": "Table sizes",
   "type": "table",
   "description": "Data from a materialized view that is refreshed only occasionally",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nselect table_schema, table_name, version, row_estimate, total_bytes, index_bytes, toast_bytes\n  from info.table_sizes"
    }
   ]
  }
 ]
}