version: '3.9'

x-logging:
  &default-logging
  options:
    max-file: '1'
    compress: 'false'
  driver: local

volumes:
  db-autoagora: {}
  rabbitmq_etc: {}
  rabbitmq_data: {}

services:
############################################
##### AUTOAGORA #####
############################################
  autoagora:
    image: ghcr.io/semiotic-ai/autoagora:v1.3.0
    container_name: ${COMPOSE_PROJECT_NAME}-autoagora
    networks:
      - indexer
    expose:
      - 8000
    volumes:
      - db-socket:/var/run/postgresql
    depends_on:
      - autoagora-indexer-service
      - postgres-autoagora
      - rabbitmq
      - autoagora-processor
    environment:
      INDEXER_AGENT_MGMT_ENDPOINT: http://${COMPOSE_PROJECT_NAME}-indexer-agent:8000
      INDEXER_SERVICE_METRICS_ENDPOINT: http://${COMPOSE_PROJECT_NAME}-indexer-service:7300/metrics
      POSTGRES_HOST: ${COMPOSE_PROJECT_NAME}-postgres-autoagora
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ${DB_AUTOAGORA_NAME}
      POSTGRES_USERNAME: ${DB_AUTOAGORA_USER}
      POSTGRES_PASSWORD: ${DB_AUTOAGORA_PASS}
      LOG_LEVEL: DEBUG
      JSON_LOGS: "true"
    logging: *default-logging
    restart: unless-stopped

############################################
##### AUTOAGORA INDEXER SERVICE #####
############################################
  autoagora-indexer-service:
    image: ghcr.io/semiotic-ai/autoagora-indexer-service:v0.1.2-v0.20.16
    container_name: ${COMPOSE_PROJECT_NAME}-indexer-service
    depends_on:
      - index-node
      - query-node
      - indexer-agent
      - postgres-indexer
    networks:
      - indexer
    expose:
      - 7300
      - 7600
    environment:
      INDEXER_SERVICE_ETHEREUM: ${TXN_RPC}
      INDEXER_SERVICE_ETHEREUM_NETWORK: ${ETHEREUM_NETWORK}
      INDEXER_SERVICE_INDEXER_ADDRESS: ${STAKING_ADDRESS}
      INDEXER_SERVICE_MNEMONIC: ${OPERATOR_MNEMONIC}
      INDEXER_SERVICE_PORT: 7600
      # INDEXER_SERVICE_NETWORK_SUBGRAPH_DEPLOYMENT: ${NETWORK_SUBGRAPH_DEPLOYMENT}
      INDEXER_SERVICE_NETWORK_SUBGRAPH_ENDPOINT: ${NETWORK_SUBGRAPH_ENDPOINT}
      INDEXER_SERVICE_CLIENT_SIGNER_ADDRESS: ${CLIENT_SIGNER_ADDRESS}
      INDEXER_SERVICE_GRAPH_NODE_QUERY_ENDPOINT: http://${COMPOSE_PROJECT_NAME}-query-node:8000
      INDEXER_SERVICE_GRAPH_NODE_STATUS_ENDPOINT: http://${COMPOSE_PROJECT_NAME}-index-node:8030/graphql
      INDEXER_SERVICE_POSTGRES_HOST: ${COMPOSE_PROJECT_NAME}-postgres-indexer
      INDEXER_SERVICE_POSTGRES_USERNAME: ${DB_INDEXER_USER}
      INDEXER_SERVICE_POSTGRES_PASSWORD: ${DB_INDEXER_PASS}
      INDEXER_SERVICE_POSTGRES_DATABASE: ${DB_INDEXER_NAME}
      VIRTUAL_HOST: ${INDEX_HOST}
      VIRTUAL_PORT: 7600
      LETSENCRYPT_HOST: ${INDEX_HOST}
      RABBITMQ_HOST: ${COMPOSE_PROJECT_NAME}-rabbitmq
      RABBITMQ_USERNAME: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
    logging: *default-logging
    restart: unless-stopped

############################################
##### AUTOAGORA PROCESSOR #####
############################################
  autoagora-processor:
    image: kwetlesen/autoagora-processor:latest
    container_name: ${COMPOSE_PROJECT_NAME}-autoagora-processor
    networks:
      - indexer
    volumes:
      - db-socket:/var/run/postgresql
    depends_on:
      - autoagora-indexer-service
      - postgres-autoagora
      - rabbitmq
    environment:
      RABBITMQ_HOST: ${COMPOSE_PROJECT_NAME}-rabbitmq
      RABBITMQ_USERNAME: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
      GRAPH_NODE_QUERY_ENDPOINT: http://${COMPOSE_PROJECT_NAME}-query-node:8000
      GRAPH_POSTGRES_HOST: ${COMPOSE_PROJECT_NAME}-postgres-node
      GRAPH_POSTGRES_DATABASE: ${DB_NODE_NAME}
      GRAPH_POSTGRES_USERNAME: ${DB_NODE_USER}
      GRAPH_POSTGRES_PASSWORD: ${DB_NODE_PASS}
      LOG_LEVEL: DEBUG
      POSTGRES_HOST: ${COMPOSE_PROJECT_NAME}-postgres-autoagora
      POSTGRES_DATABASE: ${DB_AUTOAGORA_NAME}
      POSTGRES_USERNAME: ${DB_AUTOAGORA_USER}
      POSTGRES_PASSWORD: ${DB_AUTOAGORA_PASS}
    logging: *default-logging
    restart: unless-stopped

############################################
##### AUTOAGORA DATABASE #####
############################################
  postgres-autoagora:
    image: postgres:13.6
    container_name: ${COMPOSE_PROJECT_NAME}-postgres-autoagora
    networks:
      - indexer
    profiles: ["autoagora"]
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_AUTOAGORA_USER}
      POSTGRES_PASSWORD: ${DB_AUTOAGORA_PASS}
      POSTGRES_DB: ${DB_AUTOAGORA_NAME}
    volumes:
      - db-autoagora:/var/lib/postgresql/data
    expose:
      - 5432
    logging: *default-logging

############################################
##### RABBITMQ #####
############################################
  rabbitmq:
    image: rabbitmq:3.9.25
    container_name: ${COMPOSE_PROJECT_NAME}-rabbitmq
    networks:
      - indexer
    profiles: ["autoagora"]
    volumes:
      - rabbitmq_etc:/etc/rabbitmq/
      - rabbitmq_data:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    expose:
      - 5672
      - 15672
    restart: unless-stopped