x-logging:
  &default-logging
  options:
    max-file: '1'
    compress: 'false'
  driver: local

volumes:
  db-socket:
    name: graph-node_db-socket
    external: true
  db-indexer:
    name: ${INDEXER_NAME}-indexer_db-indexer
  cli-data:
    name: ${INDEXER_NAME}-indexer_cli-data
  cli-history:
    name: ${INDEXER_NAME}-indexer_cli-history
  config:
    external: true
    name: ${INDEXER_NAME}-indexer_config

networks:
  indexer:
    name: ${INDEXER_NAME}-indexer

services:
  indexer-agent:
    image: ghcr.io/graphprotocol/indexer-agent:${INDEXER_AGENT_VERSION}
    container_name: ${INDEXER_NAME}-indexer-agent
    networks:
      - indexer
    expose:
      - 7300
      - 8000
      - 8001
      - 8002
    depends_on:
      - postgres-indexer
    environment:
      INDEXER_AGENT_NETWORK_PROVIDER: ${NETWORK_PROVIDER}
      INDEXER_AGENT_MNEMONIC: ${OPERATOR_MNEMONIC}
      INDEXER_AGENT_INDEXER_ADDRESS: ${INDEXER_ADDRESS}
      INDEXER_AGENT_GRAPH_NODE_QUERY_ENDPOINT: ${GRAPH_NODE_QUERY_ENDPOINT}
      INDEXER_AGENT_GRAPH_NODE_STATUS_ENDPOINT: ${GRAPH_NODE_STATUS_ENDPOINT}
      INDEXER_AGENT_GRAPH_NODE_ADMIN_ENDPOINT: ${GRAPH_NODE_ADMIN_ENDPOINT}
      INDEXER_AGENT_PUBLIC_INDEXER_URL: ${PUBLIC_INDEXER_URL}
      INDEXER_AGENT_INDEXER_GEO_COORDINATES: ${INDEXER_GEO_COORDINATES}
      INDEXER_AGENT_ALLOCATION_MANAGEMENT: ${ALLOCATION_MANAGEMENT}
      INDEXER_AGENT_NETWORK_SUBGRAPH_DEPLOYMENT: ${NETWORK_SUBGRAPH_DEPLOYMENT}
      INDEXER_AGENT_NETWORK_SUBGRAPH_ENDPOINT: ${NETWORK_SUBGRAPH_ENDPOINT}
      INDEXER_AGENT_TAP_SUBGRAPH_ENDPOINT: ${TAP_SUBGRAPH_ENDPOINT}
      INDEXER_AGENT_EPOCH_SUBGRAPH_ENDPOINT: ${EPOCH_SUBGRAPH_ENDPOINT}
      INDEXER_AGENT_REBATE_CLAIM_THRESHOLD: ${REBATE_CLAIM_THRESHOLD}
      INDEXER_AGENT_REBATE_CLAIM_BATCH_THRESHOLD: ${REBATE_CLAIM_BATCH_THRESHOLD}
      INDEXER_AGENT_REBATE_CLAIM_MAX_BATCH_SIZE: ${REBATE_CLAIM_MAX_BATCH_SIZE}
      INDEXER_AGENT_VOUCHER_REDEMPTION_THRESHOLD: ${VOUCHER_REDEMPTION_THRESHOLD}
      INDEXER_AGENT_VOUCHER_REDEMPTION_BATCH_THRESHOLD: ${VOUCHER_REDEMPTION_BATCH_THRESHOLD}
      INDEXER_AGENT_VOUCHER_REDEMPTION_MAX_BATCH_SIZE: ${VOUCHER_REDEMPTION_MAX_BATCH_SIZE}
      INDEXER_AGENT_GATEWAY_ENDPOINT: ${GATEWAY_ENDPOINT}
      INDEXER_AGENT_INJECT_DAI: ${INJECT_DAI}
      INDEXER_AGENT_POSTGRES_PORT: ${DB_INDEXER_PORT}
      INDEXER_AGENT_POSTGRES_HOST: ${DB_INDEXER_HOST}
      INDEXER_AGENT_POSTGRES_USERNAME: ${DB_INDEXER_USER}
      INDEXER_AGENT_POSTGRES_PASSWORD: ${DB_INDEXER_PASS}
      INDEXER_AGENT_POSTGRES_DATABASE: ${DB_INDEXER_NAME}
      INDEXER_AGENT_DAI_CONTRACT: ${DAI_CONTRACT}
      INDEXER_AGENT_SUBGRAPH_MAX_BLOCK_DISTANCE: ${SUBGRAPH_MAX_BLOCK_DISTANCE}
      INDEXER_AGENT_SUBGRAPH_FRESHNESS_SLEEP_MILLESECONDS: ${SUBGRAPH_FRESHNESS_SLEEP_MILLESECONDS}
    restart: unless-stopped
    logging: *default-logging

  indexer-service:
    image: ghcr.io/graphprotocol/indexer-service-rs:${INDEXER_SERVICE_VERSION}
    container_name: ${INDEXER_NAME}-indexer-service
    depends_on:
      - postgres-indexer
    env_file:
      - ../envs/indexer-${INDEXER_NAME}.env
    volumes:
      - config:/root/.config
    command: >
      --config /root/.config/indexer-config.toml
    environment:
      RUST_LOG: ${INDEXER_SERVICE_LOG_LEVEL:-DEBUG}
      VIRTUAL_HOST: index-${INDEXER_NAME}.${INDEXER_HOST}
      VIRTUAL_PORT: ${SERVICE_QUERY_PORT}
      LETSENCRYPT_HOST: index-${INDEXER_NAME}.${INDEXER_HOST}
    expose:
      - 7300
      - 7600
    networks:
      - indexer
    restart: unless-stopped
    logging: *default-logging

  indexer-tap:
    image: ghcr.io/graphprotocol/indexer-tap-agent:${INDEXER_TAP_VERSION}
    container_name: ${INDEXER_NAME}-indexer-tap
    networks:
      - indexer
    depends_on:
      - postgres-indexer
    env_file:
      - ../envs/indexer-${INDEXER_NAME}.env
    volumes:
      - config:/root/.config
    command: >
      --config /root/.config/indexer-config.toml
    environment:
      RUST_LOG: ${TAP_AGENT_LOG_LEVEL:-DEBUG}
      RUST_BACKTRACE: full
    expose:
      - 7300
    restart: unless-stopped
    logging: *default-logging

  indexer-cli:
    build:
      args:
        VERSION: ${INDEXER_CLI_VERSION}
        INDEXER_NAME: ${INDEXER_NAME}
      context: ../cli
      dockerfile: Dockerfile
    container_name: ${INDEXER_NAME}-indexer-cli
    networks:
      - indexer
    depends_on:
      - indexer-agent
    tty: true
    volumes:
      - cli-data:/root/data
      - cli-history:/history
    restart: unless-stopped
    logging: *default-logging

  postgres-indexer:
    image: postgres:${DB_INDEXER_VERSION}
    container_name: ${INDEXER_NAME}-postgres-indexer
    shm_size: 1gb
    networks:
      - indexer
    expose:
      - 5432
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: ${DB_INDEXER_USER}
      POSTGRES_PASSWORD: ${DB_INDEXER_PASS}
      POSTGRES_DB: ${DB_INDEXER_NAME}
    volumes:
      - db-indexer:/var/lib/postgresql/data
    restart: unless-stopped
    logging: *default-logging
