x-logging:
  &default-logging
  options:
    max-file: '1'
    compress: 'false'
  driver: local

volumes:
  db-socket:
    name: graph-node_db-socket
    external: true
  db-indexer:
    name: ${INDEXER_NAME}-indexer_db-indexer
  cli-data:
    name: ${INDEXER_NAME}-indexer_cli-data
  cli-history:
    name: ${INDEXER_NAME}-indexer_cli-history

networks:
  indexer:
    name: ${INDEXER_NAME}-indexer

services:
  indexer-agent:
    image: ghcr.io/graphprotocol/indexer-agent:${INDEXER_VERSION}
    container_name: ${INDEXER_NAME}-indexer-agent
    networks:
      - indexer
    expose:
      - 7300
      - 8000
      - 8001
      - 8002
    depends_on:
      - postgres-indexer
    environment:
      INDEXER_AGENT_NETWORK_PROVIDER: ${NETWORK_PROVIDER}
      # INDEXER_AGENT_ETHEREUM_POLLING_INTERVAL: ${ETHEREUM_POLLING_INTERVAL}
      # INDEXER_AGENT_GAS_INCREASE_TIMEOUT: ${GAS_INCREASE_TIMEOUT}
      # INDEXER_AGENT_GAS_INCREASE_FACTOR: ${GAS_INCREASE_FACTOR}
      INDEXER_AGENT_GAS_PRICE_MAX: ${GAS_PRICE_MAX}
      # INDEXER_AGENT_BASE_FEE_PER_GAS_MAX: ${BASE_FEE_PER_GAS_MAX}
      # INDEXER_AGENT_TRANSACTION_ATTEMPTS: ${TRANSACTION_ATTEMPTS}
      INDEXER_AGENT_MNEMONIC: ${MNEMONIC}
      INDEXER_AGENT_INDEXER_ADDRESS: ${INDEXER_ADDRESS}
      INDEXER_AGENT_INDEX_NODE_IDS: ${INDEX_NODE_IDS:-index_node}
      # INDEXER_AGENT_INDEXER_MANAGEMENT_PORT: ${INDEXER_MANAGEMENT_PORT}
      # INDEXER_AGENT_METRICS_PORT: ${METRICS_PORT}
      # INDEXER_AGENT_SYNCING_PORT: ${SYNCING_PORT}
      # INDEXER_AGENT_LOG_LEVEL: ${LOG_LEVEL}
      INDEXER_AGENT_GRAPH_NODE_QUERY_ENDPOINT: ${GRAPH_NODE_QUERY_ENDPOINT:-http://query-node:8000}
      INDEXER_AGENT_GRAPH_NODE_STATUS_ENDPOINT: ${GRAPH_NODE_STATUS_ENDPOINT:-http://index-node:8030/graphql}
      INDEXER_AGENT_GRAPH_NODE_ADMIN_ENDPOINT: ${GRAPH_NODE_ADMIN_ENDPOINT:-http://index-node:8020}
      # INDEXER_AGENT_ENABLE_AUTO_MIGRATION_SUPPORT: ${ENABLE_AUTO_MIGRATION_SUPPORT}
      INDEXER_AGENT_PUBLIC_INDEXER_URL: ${PUBLIC_INDEXER_URL}
      INDEXER_AGENT_INDEXER_GEO_COORDINATES: ${INDEXER_GEO_COORDINATES}
      # INDEXER_AGENT_RESTAKE_REWARDS: ${RESTAKE_REWARDS}
      INDEXER_AGENT_ALLOCATION_MANAGEMENT: ${ALLOCATION_MANAGEMENT}
      # INDEXER_AGENT_AUTO_ALLOCATION_MIN_BATCH_SIZE: ${AUTO_ALLOCATION_MIN_BATCH_SIZE}
      INDEXER_AGENT_NETWORK_SUBGRAPH_DEPLOYMENT: ${NETWORK_SUBGRAPH_DEPLOYMENT}
      INDEXER_AGENT_NETWORK_SUBGRAPH_ENDPOINT: ${NETWORK_SUBGRAPH_ENDPOINT}
      # INDEXER_AGENT_ALLOCATE_ON_NETWORK_SUBGRAPH: ${ALLOCATE_ON_NETWORK_SUBGRAPH}
      INDEXER_AGENT_EPOCH_SUBGRAPH_ENDPOINT: ${EPOCH_SUBGRAPH_ENDPOINT}
      # INDEXER_AGENT_DEFAULT_ALLOCATION_AMOUNT: ${DEFAULT_ALLOCATION_AMOUNT}
      # INDEXER_AGENT_REGISTER: ${REGISTER}
      INDEXER_AGENT_REBATE_CLAIM_THRESHOLD: ${REBATE_CLAIM_THRESHOLD}
      INDEXER_AGENT_REBATE_CLAIM_BATCH_THRESHOLD: ${REBATE_CLAIM_BATCH_THRESHOLD}
      INDEXER_AGENT_REBATE_CLAIM_MAX_BATCH_SIZE: ${REBATE_CLAIM_MAX_BATCH_SIZE}
      INDEXER_AGENT_VOUCHER_REDEMPTION_THRESHOLD: ${VOUCHER_REDEMPTION_THRESHOLD}
      INDEXER_AGENT_VOUCHER_REDEMPTION_BATCH_THRESHOLD: ${VOUCHER_REDEMPTION_BATCH_THRESHOLD}
      INDEXER_AGENT_VOUCHER_REDEMPTION_MAX_BATCH_SIZE: ${VOUCHER_REDEMPTION_MAX_BATCH_SIZE}
      INDEXER_AGENT_GATEWAY_ENDPOINT: ${GATEWAY_ENDPOINT}
      # INDEXER_AGENT_COLLECT_RECEIPTS_ENDPOINT: ${COLLECT_RECEIPTS_ENDPOINT}
      INDEXER_AGENT_INJECT_DAI: ${INJECT_DAI}
      INDEXER_AGENT_POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      INDEXER_AGENT_POSTGRES_HOST: ${POSTGRES_HOST:-${INDEXER_NAME}-postgres-indexer}
      INDEXER_AGENT_POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      INDEXER_AGENT_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      INDEXER_AGENT_POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      # INDEXER_AGENT_POSTGRES_POOL_SIZE: ${POSTGRES_POOL_SIZE}
      # INDEXER_AGENT_POI_DISPUTABLE_EPOCHS: ${POI_DISPUTABLE_EPOCHS}
      # INDEXER_AGENT_POI_DISPUTE_MONITORING: ${POI_DISPUTE_MONITORING}
      # INDEXER_AGENT_OFFCHAIN_SUBGRAPHS: ${OFFCHAIN_SUBGRAPHS}
      INDEXER_AGENT_DAI_CONTRACT: ${DAI_CONTRACT}
      INDEXER_AGENT_SUBGRAPH_MAX_BLOCK_DISTANCE: ${SUBGRAPH_MAX_BLOCK_DISTANCE}
      INDEXER_AGENT_SUBGRAPH_FRESHNESS_SLEEP_MILLESECONDS: ${SUBGRAPH_FRESHNESS_SLEEP_MILLESECONDS}
    restart: unless-stopped
    logging: *default-logging

  indexer-service:
    image: ghcr.io/graphprotocol/indexer-service:${INDEXER_VERSION}
    container_name: ${INDEXER_NAME}-indexer-service
    networks:
      - indexer
    expose:
      - 7300
      - 7600
    depends_on:
      - indexer-agent
      - postgres-indexer
    environment:
      INDEXER_SERVICE_NETWORK_PROVIDER: ${NETWORK_PROVIDER}
      # INDEXER_SERVICE_ETHEREUM_POLLING_INTERVAL : ${ETHEREUM_POLLING_INTERVAL}
      INDEXER_SERVICE_MNEMONIC: ${MNEMONIC}
      INDEXER_SERVICE_INDEXER_ADDRESS: ${INDEXER_ADDRESS}
      INDEXER_SERVICE_PORT: ${QUERY_PORT:-7600}
      # INDEXER_SERVICE_METRICS_PORT: ${METRICS_PORT}
      INDEXER_SERVICE_GRAPH_NODE_QUERY_ENDPOINT: ${GRAPH_NODE_QUERY_ENDPOINT:-http://query-node:8000}
      INDEXER_SERVICE_GRAPH_NODE_STATUS_ENDPOINT: ${GRAPH_NODE_STATUS_ENDPOINT:-http://index-node:8030/graphql}
      # INDEXER_SERVICE_LOG_LEVEL: ${LOG_LEVEL}
      # INDEXER_SERVICE_QUERY_TIMING_LOGS: ${QUERY_TIMING_LOGS}
      INDEXER_SERVICE_POSTGRES_HOST: ${POSTGRES_HOST:-${INDEXER_NAME}-postgres-indexer}
      INDEXER_SERVICE_POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      INDEXER_SERVICE_POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      INDEXER_SERVICE_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      INDEXER_SERVICE_POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      INDEXER_SERVICE_NETWORK_SUBGRAPH_DEPLOYMENT: ${NETWORK_SUBGRAPH_DEPLOYMENT}      
      INDEXER_SERVICE_NETWORK_SUBGRAPH_ENDPOINT: ${NETWORK_SUBGRAPH_ENDPOINT}
      # INDEXER_SERVICE_NETWORK_SUBGRAPH_AUTH_TOKEN: ${NETWORK_SUBGRAPH_AUTH_TOKEN}                
      # INDEXER_SERVICE_SERVE_NETWORK_SUBGRAPH: ${SERVE_NETWORK_SUBGRAPH}                              
      # INDEXER_SERVICE_ALLOCATION_SYNCING_INTERVAL: ${ALLOCATION_SYNCING_INTERVAL}                      
      # INDEXER_SERVICE_GCLOUD_PROFILING: ${GCLOUD_PROFILING}
      # INDEXER_SERVICE_FREE_QUERY_AUTH_TOKEN: ${FREE_QUERY_AUTH_TOKEN}  
      INDEXER_SERVICE_CLIENT_SIGNER_ADDRESS: ${CLIENT_SIGNER_ADDRESS}
      VIRTUAL_HOST: index-${INDEXER_NAME}.${INDEXER_HOST}
      VIRTUAL_PORT: ${QUERY_PORT:-7600}
      LETSENCRYPT_HOST: index-${INDEXER_NAME}.${INDEXER_HOST}
    restart: unless-stopped
    logging: *default-logging

  indexer-cli:
    build:
      args:
        VERSION: ${INDEXER_VERSION}
        INDEXER_NAME: ${INDEXER_NAME}
      context: ../cli
      dockerfile: Dockerfile
    container_name: ${INDEXER_NAME}-indexer-cli
    networks:
      - indexer
    depends_on:
      - indexer-agent
    tty: true
    volumes:
      - cli-data:/root/data
      - cli-history:/history
    restart: unless-stopped
    logging: *default-logging

  postgres-indexer:
    image: postgres:${DB_INDEXER_VERSION}
    container_name: ${INDEXER_NAME}-postgres-indexer
    networks:
      - indexer
    expose:
      - 5432
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - db-indexer:/var/lib/postgresql/data
    restart: unless-stopped
    logging: *default-logging