version: '3.9'

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  nginx-acme:
  nginx-htpasswd:
    external: true
    name: proxy_nginx-htpasswd
  traefik-letsencrypt:

networks:
  proxy:
    name: reverse-proxy
  
services:
############################################
############### NGINX PROXY ################
############################################
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    profiles: ["nginx"]
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-htpasswd:/etc/nginx/htpasswd
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      VIRTUAL_PROTO: https
############################################

############################################
############### NGINX SSL ##################
############################################
  nginx-ssl:
    image: nginxproxy/acme-companion
    container_name: ${COMPOSE_PROJECT_NAME}-nginx-ssl
    profiles: ["nginx"]
    networks:
      - proxy
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - nginx-certs:/etc/nginx/certs:rw
      - nginx-acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: ${COMPOSE_PROJECT_NAME}-nginx
      DEFAULT_EMAIL: ${EMAIL}
############################################

############################################
###############  TRAEFIK  ##################
############################################
  traefik:
    image: traefik
    container_name: ${COMPOSE_PROJECT_NAME}-traefik
    profiles: ["traefik"]
    restart: always
    networks:
      - proxy
    ports:
      - "443:443"
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=$EMAIL"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "traefik-letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.ipwhitelist.ipwhitelist.sourcerange=$WHITELIST"
############################################